### ISSUE TITLE
🔴 Crash after Nack

### ISSUE THREAD

**Issue by DiCesareDaniele** [WGL-2024/WGL_repo_2024#64]
## 🔴 Crash after Nack
What do we do if a drone in the source routing is crashed during a nack (expected to always arrive at destination).
> In real world, clients and servers use timeouts to infer that a packet has been dropped or that a drone has crashed. In this project, for simplification, these failures are notified to clients and servers as specific messages that cannot be dropped by drones

Example:
```mermaid
flowchart LR;
D1(D1);
D2(D2);
D3(D3);
C1 <--> D1;
C1 <--> D2;
D1 <--> D3;
D2 <--> D3;
D3 <--> S1;
```
C1 wants to send a message to S1 (path: [C1, D1, D3, S1])
The packet gets dropped at D3 so D3 is going to sends a Nack to C1 (path: [D3, D1, C1]).
> If an error occurs, then a Nack is sent.
Source Routing Header contains the path to the client, which can be obtained by reversing the list of hops contained in the Source Routing Header of the problematic Message.

Meanwhile D1 receved a command from the controller to crash. The packet cannot arrive at C1 and the drone cannot find another route since the drones do not keep routing tables even tho the path exists.
> Clients and servers use source routing: the path that a packet takes through the drone network is determined by the client and server themselves instead of routers. The consequence is that drones do not maintain routing tables.

### Proposal
Send nack message from drone to controller and then let the controller forward that information to the client/server. The assumption that the nack could not be dropped was already irrealistic so the fact that we receve the nack from the controller is not that dumb. But I am open to other proposals about this one because I don't love this fix.

**Comment by matteo-dinoia** [comment]
Better than nothing

**Comment by luiss07** [comment]
This problem has to be considered also when a Client/Sever tries to send a Packet but the Path contains a crashed drone. From the main specification:
> The packets must be eventually delivered at servers and clients. This must be accomplished by clients and servers with the use protocols. In real world, clients and servers use timeouts to infer that a packet has been dropped or that a drone has crashed. In this project, for simplification, these failures are notified to clients and servers as specific messages that cannot be dropped by drones.

Thus, when the Packet will eventually reach the crashed drone we need a way to tell the Client/Server sending the packet that the Packet reached a dead end (Nack). 

 I think we have three options:
- Your proposal of using the controller
- Create a Broadcast to tell all the client / server that it crashed 
- Putting the drone thread in a sleeping state (i.e. using an enum)

I would go with either the second or third. Since they do not involve the controller. The second is more "realistic" but inefficient, and the third is a workaround.

Using the second one, the Client/Sever should handle the error (i.e. change the SourceRouting path and send again the whole Message)

In the third one, the drone would not be killed but the thread would be "sleeping" through the set of a variable. In this way, when a drone is crashed, it can still listen to the incoming request and if it is in a `Crashed` state it will answer with a `Nack(Crashed)`.

Let me know. Eventually I can work on a PR.

**Comment by DiCesareDaniele** [comment]
I like both options but. The second it's more difficult. We could use the second also to update of the routing tables of server/client

**Comment by luiss07** [comment]
Yes, it is definitely more difficult since we need to modify the Flooding packages or create a new one. Then, on the Client/Server side, the handling becomes more difficult because you don't know at which point of the communication the drone crashed.

Instead with the sleeping thread, we can just answer with a nack containing some information about the crashed drone and the packet that has not been forwarded and still be able to update the routing tables (in my head easier and preferable?)

I guess it is just a matter of how much we want to complicate our lives 😂

**Comment by DiCesareDaniele** [comment]
> I guess it is just a matter of how much we want to complicate our lives 😂

Agree 😂

**Comment by matteo-dinoia** [comment]
I would go with the first, honestly. 
The second is fine and more realistic but is harder and we already behind. Also the professor is ok with us using the first method.
The third in my opinion is not good at all.

**Comment by luiss07** [comment]
I mean, the third option would also remove the bother of killing and spawning a new thread every time (without having to go through the SC). Anyway, do you think it might be better to have the 3 proposals explained (in a really abstract way) and the WG can vote or just vote on the first PR that we see?

**Comment by DiCesareDaniele** [comment]
> Anyway, do you think it might be better to have the 3 proposals explained (in a really abstract way) and the WG can vote or just vote on the first PR that we see?

I would talk about it at the next WG

**Comment by Marui-9** [comment]
You all have a point. We'll talk about this. The option of using the controller seems better conceptually because it should be the controller to orchestrate this kind of stuff (the crashes). However, if the third option is easier I'd rather go with that one. Just sending a Nack with some information sounds good. Thank you for bringing this up

**Comment by Suge42** [comment]
This is quite a difficult topic indeed, mainly because for the network the controller shouldn't exist. We know it's there and it communicates with the nodes, but it's not a part of the network, so it wouldn't be the best to use it to deliver messages.
My guess is that the professor would avoid something like this to happen, but this needs some discussion when the main parts of the protocol will be ready I think.
It's a bit like when we ended up talking about how to add channels to a drone when a new one is added. Yes is a problem, but if we don't have working drones yet, it shouldn't be our priority maybe

**Comment by DiCesareDaniele** [comment]
You are right, but I don't think passing through the controller would be the end of the world cause there are already some unrealistic assumptions like this. If our goal was a realistic network implementation we would add a timer to understand if the packet was dropped

**Comment by matteo-dinoia** [comment]
> This is quite a difficult topic indeed, mainly because for the network the controller shouldn't exist. We know it's there and it communicates with the nodes, but it's not a part of the network, so it wouldn't be the best to use it to deliver messages.
> My guess is that the professor would avoid something like this to happen, but this needs some discussion when the main parts of the protocol will be ready I think.
> It's a bit like when we ended up talking about how to add channels to a drone when a new one is added. Yes is a problem, but if we don't have working drones yet, it shouldn't be our priority maybe

The professor is fine with passing for simulation controller for this cases. I asked him. He said that for this case being an edge cases that should not happen is totally fine to pass via SC. He also said not to complicate our life when we don't have the foundamentals.

**Comment by saussice9** [comment]
I'm agree with using the controller but only when we haven't any other choice. I mean a Nack can in most of the case reach the sender of a non-delivered message but if the drone see he cannot send is Nack to the next hop he send it to the simulation controller insted. Then the simulation Controller can send it direcly to the sender.

For me it's better like this but it's just a suggestion

**Comment by matteo-dinoia** [comment]
That was the idea. Maybe we were not clear.

**Comment by Suge42** [comment]
I think that this discussion was left incomplete, mainly because we should need to come to a conclusion with what to do with Nacks, Acks, and maybe FloodResponses.

Would someone be able to do a PR about this to be voted?

**Comment by DiCesareDaniele** [comment]
> I think that this discussion was left incomplete, mainly because we should need to come to a conclusion with what to do with Nacks, Acks, and maybe FloodResponses.
> 
> Would someone be able to do a PR about this to be voted?

This is part of a broader argument which is what to do with crashes and nack in general since now it's not clear. I would like to discuss this at the next wg since it's really important. I'll proced to improve the description of this pr so the problem it's clearer

**Comment by Suge42** [comment]
> This is part of a broader argument which is what to do with crashes and nack in general since now it's not clear. I would like to discuss this at the next wg since it's really important. I'll proced to improve the description of this pr so the problem it's clearer

Okok, the clearer the better, since we have very few days left to work on deez, and still a lot of stuff to talk about :')

**Comment by marcoff181** [comment]
At this point, given that this is related to #84, and the fact that the proposed option 1 and option 2 of #84 do not address this issue, so they are incomplete, we could modify the presentation of that PR, changing the section of the other options with what you are proposing here. I think that discussing about this issue without seeing the other PR wouldn't make sense, and the opposite is also true

**Comment by marcoff181** [comment]
Instead of having to switch between the two during the WG

**Comment by marcoff181** [comment]
I can also remove option 1 and 2 from pr #84, given that they do not handle all cases, and you can write in this or in a PR how you would handle crash in general using simulation controller, while also considering the issue presented here. Because at the moment we don't have any working implementation of a counter PR to #84

**Comment by DiCesareDaniele** [comment]
Agree 100%

**Comment by marcoff181** [comment]
> Agree 100%

Okay, this evening I'll remove the option 1 and 2 from my pr

**Comment by marcoff181** [comment]
I can leave them if you want but they don't consider the option that a nack travelling back to the client has a route that includes a crashed drone, even if it crashed safely as in opt1 and opt2

**Comment by Suge42** [comment]
Last time I asked the professor, he said that it would be better to avoid timers.
The best solution to implement would be to pass through the Simulation Controller if we encounter a crashed drone on out way.
For the channels, it's better to close the neighbour channels, empty the channel, and then crush the drone.

To make it simple, no timers.

I would usually prefer to leave the discussion and conclusions to the groups, but we don't have any time left to discuss and leave 4 different option from which we can't find a common choice.

**Comment by marcoff181** [comment]
The issue is that by not having timeouts we are complicating things😂

I think that given that this is one of the most divisive topics the WG should discuss and vote this, given that the professor hasn't given a hard no on the timeout
