### ISSUE TITLE
What are the packages for which a Nack can be sent? Not for FloodResponse

### ISSUE THREAD

**Issue by RickyBenevelli** [WGL-2024/WGL_repo_2024#98]
In my opinion, the only PacketType for which a Nack can be sent is the `MsgFragment` type.

I read in the PR #94 discussion that someone would like to send Nack for other things as well, such as for `FloodResponse` packets that might be lost due to a crashed drone. In my opinion it does not make sense to send back a Nack in this case since the drone from which the `FloodResponse` packet originated has no way of knowing which one was lost and which one to send back and from where to send it back. 

Currently the best solution I have is to be aware that we might lose a `FloodResponse` (and thus have partial knowledge of the network). However at the next flooding we will probably be able to recover.

**Comment by Suge42** [comment]
The types of packets can be:
- MsgFragment, which can send a Nack
- Nack, which shouldn't get lost, but we don't really have a solution for that still
- Ack, same as Nack
- FloodRequest, which it might be fine to not send to a crashed node, but if the current node has only the receiving one and the crashed one, we should probably send a FloodResponse back, otherwise we might loose information
- FloodResponse, which shouldn't get lost probably

**Comment by matteo-dinoia** [comment]
Flood can be easily lost, as we don't care much. We can always flood again if the topology is not enough to send the packet.

**Comment by matteo-dinoia** [comment]
Nack and ack we are voting right now if i'm not wrong.

**Comment by RickyBenevelli** [comment]
> Nack and ack we are voting right now if i'm not wrong.

I don't think so. They are currently voting to reverse the changes due to the incorrect merge of PR #90

**Comment by RickyBenevelli** [comment]
I think it is important to agree that we should not send `Nack` for `FloodResponse`.
Then when we find a way to solve issue #64 by having `Nack` and `Ack` always arrive at their destination, the `MsgFragment`s will be the only ones that need `Nack`

**Comment by matteo-dinoia** [comment]
Let's merge all the voted change about crashing node in a single PR.
